pub mod where_my_anagrams_at;
pub mod create_phone_number;
pub mod stop_gninnips_my_sdrow;
pub mod valid_parentheses;
pub mod maximum_subarray_sum;
pub mod help_the_bookseller;
pub mod best_travel;
pub mod find_the_smallest;
pub mod simple_assembler_interpreter;
