---
name: Build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and run
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust environment
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.62

      - name: Build solution
        run: cargo build

      - name: Run tests
        run: cargo test
